---
env:
  HELLO_TEXT: "Hello, pipeline!"

steps:
  - command: "./greetings.sh $$HELLO_TEXT"
    env:
      HELLO_TEXT: "Hello, step!"
  - command: "./greetings.sh $$HELLO_TEXT"
  - commands:
      - "unset HELLO_TEXT"
      - "./greetings.sh $$HELLO_TEXT"
