---
steps:
  - command: "ls -la"
  - command: "ls -la"
  - command: "ls -la"
  - command: "ls -la"
  - command: "ls -la"
  - command: "ls -la"
  - command: "ls -la"
  - command: "ls -la"
  - command: "echo 'Hello, world!'"
